/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package evaluations;

import evaluations.level11.gameobjects.SpaceShip;

public class App {

    public static void main(String[] args) {
        SpaceShip spaceship = new SpaceShip("Galactic Cruiser", 5, 0, 0);
        spaceship.displayStatus();
        spaceship.moveUp();
        spaceship.moveRight();
        spaceship.displayStatus();
        spaceship.refuel(3);
        spaceship.display();
    }
}
